VoidHub.Features = {
    "Fly",
    "Speed",
    "Jump Boost",
    "Dash",
    "Dash Power",
    "Super Auto Click",
    "Auto Farm",
    "Auto Quest",
    "Auto Collect",
    "Auto Sell",
    "Auto Fishing",
    "Perfect Cast",
    "Perfect Catch",
    "ESP",
    "Teleport",
    "FPS Counter",
    "Ping",
    "Settings",
    "Anti AFK",
    "Rejoin",
    "Server Hop",
    "Performance Mode",
    "Graphics",
    "Keybinds",
    "UI Scale",
    "Notifications",
    "Theme",
    "Debug Mode"
}

